apiVersion: business.pagerduty.m.crossplane.io/v1alpha1
kind: Service
metadata:
  annotations:
    meta.upbound.io/example-id: business/v1alpha1/service
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    description: A very descriptive description of this business service
    name: My Web App
    pointOfContact: PagerDuty Admin
    teamSelector:
      matchLabels:
        testing.upbound.io/example-name: example
